image:
  repository: wordpress
  tag: 6.6.2
  pullPolicy: IfNotPresent
deployment:
  port: 80
  replicas: 1
persistence:
  enabled: true
  name: wordpress-storage
  accessMode: ReadWriteOnce
  size: 8Gi
service:
  type: LoadBalancer
  port: 80
