apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app: {{ include "wordpress.fullname" . }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicet.port }}
      targetPort: {{ .Values.deployment.port }}
  type: {{ .Values.servicet.type }}
