name: Deploy to Kubernetes Cluster

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - task_*

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  TERRAFORM_VERSION: '1.9.6'
  AWS_GHA_ROLE: 'arn:aws:iam::035511759406:role/GithubActionsRole'
  AWS_REGION: 'us-east-1'

jobs:
  k8s:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Check k8s nodes
        run: |
          kubectl get nodes

      - name: Deploy of chart using helm
        run: |
          helm upgrade --install app-chart ./Chart
